name: dnd
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^3.26.0
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.0

  file_picker: any

  plugin_platform_interface: ^2.0.0
  firebase_core: ^1.0.0
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.14.0
  build_runner: ^1.11.5

flutter:
  uses-material-design: true
